= CICD Management for the Organization

This document will summarize the design and concepts around a group of GitHub Actions workflows that will fulfill the following goals:

* Create a standardized set of workflows based on GitHub Actions for use across the organization.
* Automate the onboarding of component GitHub repositories into the CICD framework.
* Limit the amount of work developers need to do integrate and use the CICD system.
    ** Ideally only a configuration file to be processed by the CICD system.
* The framework should require minimal maintenance by the CICD team.
* Extending the framework should be simple and by convention.

== Assumptions

* Promotion will be automated (i.e. promoting from one SDLC environment to the next will not be manual).
* Every environment will run tests after deployment.
* GitHub and Kubernetes/Openshift Cluster credentials are GitHub secrets.
* Each Git repository will consist of exactly one component or microservice.
* Readers are familiar with Git, GitHub Actions, and Kubernetes.

== Design

The design assumes three separate functional goals for the system:

* _Onboarding_: Bringing a Git repository under control of the CICD system
* _Build from Source_: Build a Git repository into an OCI compliant image and push to an image registry
* _Promotion and Deployment_: Promote the image to the next environment if already deployed, and deploy the image into the container orchestration platform

=== CICD Management Repository and Directory Structure

* *cicd-manger*: CICD Management repository.  Should be private to organization, and no one should have access outside of infra and/or CICD privileged users to protect organization GitHub Secrets.
  ** *.github*
    *** *CODEOWNERS* (file): GitHub specific file for setting permissions within a directory.  Ensures only infra and/or CICD privileged users will be able to push changes or approve pull requests to the workflows realized from this directory in a component Git repository.
    *** *run-step*
      *** _action.yml_: custom GitHub Action for finding and running shell scripts based on <<Codebase,codebase>> and workflow job step labels.
      *** *steps*: Contains all directories for each <<Codebase,codebase>>
        **** *<codebase id>*: Directories named for each <<Codebase,codebase>> ID, and the naming convention helps with leveraging the <<Run Steps,run step>> framework.  Each directory will contain a set of scripts specific to the <<Codebase,codebase>> and named corresponding the actual step defined in the workflow.
    *** *system-defs*: Contains all <<System Definitions,system definitions>>
    *** *workflows*: Contains the onboarding workflow and templates for the system repository workflows (<workflow>.yml.template files).
  ** *resources*: Contains any resources needed by the onboarding process.
    *** *resource-quotas*: Contains resource quota defintions for SDLC environments.
 
=== System Definitions

Collections of related software components, each in an individual Git repository, will be defined in a YAML based configuration file owned and managed by the CICD team.  Each configuration file will define the <<Codebase,codebase>> the component was developed with and the Git repo where the component resides.  It will also contain a list of test environments the CICD system should provide to support each components SDLC (optional).

[#sample-system-def]
.sample-system-def.yml
[source,YAML]
----
# Team the system repositories belong to
team: team-a
# Development branch of current release to build from
branch: development
# List of all components that make up a system; should correspond to a single OCP namespace
components:
    # GitHub repository
  - repo: cicd-poc-app-1
    # java11 is an example of a codebase ID
    codebase: java11
    # "status" example of an arbitrary, extra property end users of the system may add at their convenience
    status: active
  - repo: cicd-poc-app-2
    # node16 is an example of a codebase ID
    codebase: node16
    status: active
    overrides:
      # example of a component specific override for tests in the CICD system
      test: jest
# label to be used for the development environment (where builds are initially deployed)
dev-environment: dev
# label to be used for the production environment
prod-environment: prod
# arbitrary list of test environments, in order, reflecting SDLC of system
# NOTE: promotion across environments will be dev -> test-environments -> prod
test-environments:
  - qa
  - uat
  - stg
# Map of ResourceQuotas to apply to each SDLC environment
resource-quotas:
  dev: small
  qa: medium
  uat: medium
  stg: medium
  prod: large
----

==== System Definition Naming Scheme

The system definition file should be named after the system.  System definitions are looked up by file name in the `.github/system-defs` directory in the `cicd-manager` repository.

==== Codebase

An arbitrary ID created by the organization and assigned to each repository to designate the platform and language of a set of repositories.  This ID is used by the <<Run Steps,run-step>> framework to determine which scripts to run.

==== Dev, Prod, and Test Environments

Each system must have a dev and prod environment defined.  Images are built from the development branch of each repository listed in the system.  Each image is deployed initially to the dev environment.  Promotion will occur across each test environment in the order listed, and ultimately to prod, assuming a successful deployment in the previous system.  This will occur automatically, following a strategy of [Continuous Deployment].  Automated deployments to prod will *not* be implemented.

__NOTE: deployment to production is not currently implemented in this PoC.__

==== Resource Quotas

ResourceQuotas are defined in the `resource-quotas` directory in the `cicd-manager` repository, and are found by name; e.g. a SDLC environment defined with a `medium` resource quota in the system defintion file will look for a `medium.yml` in the resource-quotas directory.

=== Reusable Workflows

GitHub Actions enables reusable workflows.  This CICD system utilizes that feature to centralize the workflows for the organization.  Any workflows that exist in an individual component repository should be skeletal and call the reusable workflows.

=== Run Steps

A homegrown https://en.wikipedia.org/wiki/Convention_over_configuration[convention-over-configuration] framework for injecting scripts into the CICD system's workflows.  Depending on the <<Codebase,codebase>> ID used, scripts will be called from the `run-step` action; e.g.:

.Example of a GitHub Action Step using the run-step action in a GitHub Action workflow
[source,YAML]
----
    - id: test
      name: test
      uses: corp-org-name/cicd-manager/run-step@main
      with:
        label: ${{ env.CODEBASE }}
        step-name: test
----

In the above example, the _label_ will determine which directory in the `run-step` directory in which to look for the script (stored in and read the GitHub actions environment), and the `step-name` will determine the name of the script to run; e.g. the above example defines will look in the directory named after the current `CODEBASE` (e.g. `java11` or `node16`) being built and execute `test.sh`.

==== Overriding Run Steps

In order to reduce duplication where only a single run step needs to change, the run step may be overridden in the <<System Definitions, System Definition File>> by providing an override key/value pair.  In the example system definition <<sample-system-def,example>> above, the `test` step is overridden to run the `jest.sh` script in the `cicd-manager/run-step/node16` directory, rather than the default `test.sh` expected by default by the test run step.  The workflow calls remain unchanged as above.

==== System Onboarding and Manager

System onboarding is process of bringing all the GitHub repositories of a system under the control of the CICD system, and the workflow defined by `onboard-system.yml` in the `cicd-manager` repository automates this process.  The workflow will realize and copy the `.github` folder in the `cicd-manager` repository into a each system component repository, realize each templated workflow, and commit and push the changes back to each system component's GitHub repository.  The main template is `build.yml.template`, and it is designed as a skeleton workflow that calls the reusable workflows defined in `build-from-source.yml.template` and `promote.yml.template`.

==== Build

After a component repository is brought onboard, the build workflow will be in `build-from-source.yml`.  The steps are summarized as follows:

* Check out the source
* Build the source (if necessary)
* Run unit tests
* Scan the source and artifacts
* Build the image
* Scan the image
* Push the image to a registry

Since building, testing, and scanning will be different given the platform, language, testing frameworks, etc., the <<Codebase,codebase>> ID in the <<System Definitions,system definition file>> is used by the <<Run Steps,run step>> framework to determine how a repository is built, tested, and scanned.
 [TBD: currently undefined]
 
=== Promote and Deploy

Image promotion and deployment is governed by a single workflow `promote.yml`.  The workflow first deploys to the development environment directly after the <<Build,build>> takes place, and then uses a GitHub Action matrix to optionally deploy to any test environments defined int the <<System Definitions, System Definition File>>.  The matrix is able to run serially instead of in parallel thanks to the `max-parallel` value being set to one.

.Environment matrix from promote.yml
[source,YAML]
----
strategy:
  max-parallel: 1
  matrix:
    environment: ${{ fromJSON(inputs.environments) }}
----

Promotion should involve three basic steps:

* Copying (or re-tagging) the image built in the <<Build, build>> step
* Deploying the image to the new environment
* Running any integration tests in the new environment.

If the image deploys properly and the tests pass, then promotion to the next environment is automatically run; otherwise, the workflow fails.

The initial deployment to a "dev" environment will take place immediately after the image is built and pushed to the image registry.  After that, the image will be promoted, deployed, and tested for each of the listed test environments in the <<System Definitions, System Definition File>>; e.g.

.Sample list of environments in a system definition file
[source,YAML]
----
test-environments:
  - qa
  - uat
  - stg
----

==== Integration Test Step [TBD: currently undefined]

The integration test step will launch a Job in the component environment to run the tests from there.  The logs generated from the Job will be tailed for viewing in the GitHub Actions logs.

===== Production Promotion and Deployment [TBD: currently undefined]

It is expected that promotion to a production environment for final release will happen in a separate workflow call than that of the initial build and promote workflow.

=== Component Repository Workflow Templates

==== Build and Promote

There is currently only one workflow templated for insertion into each component repository, and it first calls the centralized, reusable <<Build,build>> workflow, parses the <<System Definition File,system definition file>> for itself to get the test environments for its SDLC, and then calls the <<Promote and Deploy,promotion>> centralized, reusable workflow.  When a component is <<System Onboarding,onboarded>> the template will be realized and copied, committed, and pushed into the component repository for use by the developer.

==== Promote to Production [TBD: currently undefined]

Promote to production, to potentially include:

* Canary and/or blue/green deployments
* Approval process
