apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: large-pods
  spec:
    hard:
      limits.cpu: "16"
      limits.memory: 95Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: large-storage
  spec:
    hard:
      requests.storage: 1024Gi