apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: medium-pods
  spec:
    hard:
      limits.cpu: "8"
      limits.memory: 48Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: medium-storage
  spec:
    hard:
      requests.storage: 256Gi