apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: small-pods
  spec:
    hard:
      limits.cpu: "4"
      limits.memory: 10Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: small-storage
  spec:
    hard:
      requests.storage: 25Gi